name: Build Common Packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: Server-Independent packages to build (comma separated)
        required: true
        default: "etcd,pgbadger,pgbouncer,pysyncobj,ydiff,h3"

      packaging-repo:
        description: packaging repo to be used
        default: percona/postgres-packaging
        required: true

      packaging-branch:
        description: packaging branch to be used
        default: main
        required: true

      pg-major:
        description: Postgres major version for which package will be built
        required: true
        default: "16"
        type: choice
        options:
          - "18"
          - "17"
          - "16"
          - "15"
          - "14"

      distro:
        description: RPM/Deb
        required: true
        default: both
        type: choice
        options:
          - "rpm-and-deb"
          - "rpm"
          - "deb"

      debugging:
        description: tmate session required
        default: false
        type: boolean

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        
jobs:
  prepare-matrix:
   runs-on: ubuntu-latest
   outputs:
      BUILD_ID: ${{ steps.set-buildID.outputs.build_id }}
      PKG_MATRIX: ${{ steps.set-pkg-matrix.outputs.pkg_matrix }}
      SOURCE_MATRIX: ${{ steps.set-source-matrix.outputs.source_matrix }}
      BUILD_MATRIX: ${{ steps.set-build-matrix.outputs.build_matrix }}

   steps:
     - name: Set timestamp
       run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

     - name: Set Build ID
       id: set-buildID
       run: echo "build_id=${{ env.TIMESTAMP }}/${GITHUB_RUN_NUMBER}" >> "$GITHUB_OUTPUT"

     - name: Set Package Matrix
       id: set-pkg-matrix
       run: |
          PKG_MATRIX=$(echo "${{ inputs.packages }}" | tr -d ' ' | jq -c -R 'split(",") | {pkgs: .}')
          echo "pkg_matrix=$PKG_MATRIX" >> $GITHUB_OUTPUT

     - name: Set source rpm/deb matrix
       id: set-source-matrix
       run: |
          PKG=$(echo "${{ inputs.packages }}" | tr -d ' ' | jq -c -R 'split(",")')
          if [ "${{ inputs.distro }}" = "rpm" ]; then
            PLATFORM='["oraclelinux:8"]'
          elif [ "${{ inputs.distro }}" = "deb" ]; then
            PLATFORM='["ubuntu:jammy"]'
          else
            PLATFORM='["oraclelinux:8","ubuntu:jammy"]'
          fi
          SOURCE_MATRIX=$(jq -c -n \
              --argjson pkgs "$PKG" \
              --argjson platform "$PLATFORM" \
              '{pkgs:$pkgs, platform:$platform}')
          echo "source_matrix=$SOURCE_MATRIX" >> $GITHUB_OUTPUT

     - name: Set rpm/deb build matrix
       id: set-build-matrix
       run: |
          ARCH='["amd64","arm64"]'
          PKG=$(echo "${{ inputs.packages }}" | tr -d ' ' | jq -c -R 'split(",")')
          if [ "${{ inputs.distro }}" = "rpm" ]; then
            PLATFORM='["oraclelinux:8","oraclelinux:9","oraclelinux:10"]'
          elif [ "${{ inputs.distro }}" = "deb" ]; then
            PLATFORM='["ubuntu:noble","ubuntu:jammy","debian:bookworm","debian:bullseye","debian:trixie"]'
          else
            PLATFORM='["oraclelinux:8","oraclelinux:9","oraclelinux:10","ubuntu:noble","ubuntu:jammy","debian:bookworm","debian:bullseye","debian:trixie"]'
          fi
          BUILD_MATRIX=$(jq -c -n \
            --argjson pkgs "$PKG" \
            --argjson platform "$PLATFORM" \
            --argjson arch "$ARCH" \
            '{pkgs:$pkgs, platform:$platform, arch:$arch}')
          echo "build_matrix=$BUILD_MATRIX" >> $GITHUB_OUTPUT

  pull-build-files:
    runs-on: ubuntu-latest
    needs: [prepare-matrix]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.PKG_MATRIX) }}

    steps:
      - name: Checkout packaging repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          repository: ${{ inputs.packaging-repo }}
          ref: main
          path: main-src

      - name: Create build files directory
        run: mkdir pkg

      - name: Collect common files
        run: |
          cp main-src/common/common-functions.sh pkg/
          cp main-src/common/install-deps.sh pkg/
          cp main-src/common/versions.sh pkg/
          cp main-src/common/${{ matrix.pkgs }}/*builder.sh pkg/pkg-builder.sh
        shell: bash

      - name: Upload build files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files-${{ matrix.pkgs }}
          path: pkg/
          
  build-source-tarball:
    runs-on: ubuntu-latest
    needs: [prepare-matrix, pull-build-files]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.PKG_MATRIX) }}

    steps:
      - name: Get build-files from artifact
        uses: actions/download-artifact@v5
        with:
          name: build-files-${{ matrix.pkgs }}
          path: ./

      - name: Update permissions of the build scripts
        run: |
          chmod 755 *.sh
        shell: bash

      - name: Build Sources
        run: |
          mkdir test
          sudo -E bash ./pkg-builder.sh --builddir=$(pwd)/test --get_sources=1 --pg_major=${{ inputs.pg-major }}
        shell: bash

      - name: Upload source tarballs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkgs }}-source_tarball
          path: source_tarball

  build-etcd-arm-source-tarball:
    if: ${{ contains(inputs.packages, 'etcd') }}
    runs-on: ubuntu-24.04-arm
    needs: [prepare-matrix, pull-build-files]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.PKG_MATRIX) }}

    steps:
      - name: Get build-files from artifact
        uses: actions/download-artifact@v5
        with:
          name: build-files-${{ matrix.pkgs }}
          path: ./

      - name: Update permissions of the build scripts
        run: |
          chmod 755 *.sh
        shell: bash

      - name: Build Sources
        run: |
          mkdir test
          sudo -E bash ./pkg-builder.sh --builddir=$(pwd)/test --get_sources=1 --pg_major=${{ inputs.pg-major }}
        shell: bash

      - name: Upload source tarballs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: etcd-arm-source_tarball
          path: source_tarball

  build-etcd-arm-srpm-sdeb:
    if: ${{ contains(inputs.packages, 'etcd') }}
    runs-on: ubuntu-24.04-arm
    needs: [prepare-matrix, pull-build-files, build-etcd-arm-source-tarball]

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.SOURCE_MATRIX) }}

    container:
      image: ${{ matrix.platform }}

    steps:
      - name: Check OS
        run: cat /etc/os-release

      - name: Install build tools
        run: |
          if [[ "${{ matrix.platform }}" == *"linux"* ]]; then
            yum install -y gcc make tar rpm-build rpmdevtools git sudo
          else
            apt-get update
            apt-get install -y wget curl gcc tar git build-essential devscripts debhelper fakeroot lintian sudo
          fi
          echo "Ready to build!"

      - name: Get build files from artifact
        uses: actions/download-artifact@v5
        with:
          name: build-files-${{ matrix.pkgs }}
          path: ./

      - name: Update permissions of the build scripts
        run: |
          chmod 755 *.sh
        shell: bash

      - name: Get source tarball from artifact
        uses: actions/download-artifact@v5
        with:
          name: etcd-arm-source_tarball
          path: test/source_tarball/

      - name: Install dependencies
        run: |
          sudo bash ./pkg-builder.sh --builddir=$(pwd)/test --install_deps=1 --pg_major=${{ inputs.pg-major }}
        shell: bash

      - name: Build Source RPM/DEB
        run: |
          if [[ "${{ matrix.platform }}" == *"linux"* ]]; then
            sudo bash ./pkg-builder.sh --builddir=$(pwd)/test --build_src_rpm=1 --pg_major=${{ inputs.pg-major }}
          else
            sudo bash ./pkg-builder.sh --builddir=$(pwd)/test --build_src_deb=1 --pg_major=${{ inputs.pg-major }}
          fi
        shell: bash

      - name: Upload source rpm as artifact
        if: ${{ contains(matrix.platform, 'linux') }}
        uses: actions/upload-artifact@v4
        with:
          name: etcd-arm-srpm
          path: srpm

      - name: Upload source deb as artifact
        if: ${{ !contains(matrix.platform, 'linux') }}
        uses: actions/upload-artifact@v4
        with:
          name: etcd-arm-source_deb
          path: source_deb

  build-srpm-sdeb:
    runs-on: ubuntu-latest
    needs: [prepare-matrix, pull-build-files, build-source-tarball]

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.SOURCE_MATRIX) }}

    container:
      image: ${{ matrix.platform }}

    steps:
      - name: Check OS
        run: cat /etc/os-release

      - name: Install build tools
        run: |
          if [[ "${{ matrix.platform }}" == *"linux"* ]]; then
            yum install -y gcc make tar rpm-build rpmdevtools git sudo
          else
            apt-get update
            apt-get install -y wget curl gcc tar git build-essential devscripts debhelper fakeroot lintian sudo
          fi
          echo "Ready to build!"

      - name: Get build files from artifact
        uses: actions/download-artifact@v5
        with:
          name: build-files-${{ matrix.pkgs }}
          path: ./

      - name: Update permissions of the build scripts
        run: |
          chmod 755 *.sh
        shell: bash

      - name: Get source tarball from artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ matrix.pkgs }}-source_tarball
          path: test/source_tarball/

      - name: Install dependencies
        run: |
          sudo bash ./pkg-builder.sh --builddir=$(pwd)/test --install_deps=1 --pg_major=${{ inputs.pg-major }}
        shell: bash

      - name: Build Source RPM/DEB
        run: |
          if [[ "${{ matrix.platform }}" == *"linux"* ]]; then
            sudo bash ./pkg-builder.sh --builddir=$(pwd)/test --build_src_rpm=1 --pg_major=${{ inputs.pg-major }}
          else
            sudo bash ./pkg-builder.sh --builddir=$(pwd)/test --build_src_deb=1 --pg_major=${{ inputs.pg-major }}
          fi
        shell: bash

      - name: Upload source rpm as artifact
        if: ${{ contains(matrix.platform, 'linux') }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkgs }}-srpm
          path: srpm

      - name: Upload source deb as artifact
        if: ${{ !contains(matrix.platform, 'linux') }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkgs }}-source_deb
          path: source_deb

  build-rpm-deb:
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    needs: [prepare-matrix, pull-build-files, build-source-tarball, build-srpm-sdeb]

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.BUILD_MATRIX) }}

    container:
      image: ${{ matrix.platform }}

    steps:
      - name: Check OS
        run: cat /etc/os-release

      - name: Install build tools
        run: |
          if [[ "${{ matrix.platform }}" == *"linux"* ]]; then
            yum install -y gcc make tar rpm-build rpmdevtools git sudo
          else
            apt-get update
            apt-get install -y wget curl gcc tar git build-essential devscripts debhelper fakeroot lintian sudo
          fi
          echo "Ready to build!"

      - name: Get build-files from artifact
        uses: actions/download-artifact@v5
        with:
          name: build-files-${{ matrix.pkgs }}
          path: ./

      - name: Update permissions of the build scripts
        run: |
          chmod 755 *.sh
        shell: bash

      - name: Get source tarball from artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ matrix.pkgs }}-source_tarball
          path: test/source_tarball/

      - name: Get source rpm from artifact
        if: ${{ contains(matrix.platform, 'linux') }}
        uses: actions/download-artifact@v5
        with:
          name: ${{ matrix.pkgs }}-srpm
          path: test/srpm/

      - name: Get source deb from artifact
        if: ${{ !contains(matrix.platform, 'linux') }}
        uses: actions/download-artifact@v5
        with:
          name: ${{ matrix.pkgs }}-source_deb
          path: test/source_deb/

      - name: Get source tarball from artifact
        if: ${{ matrix.arch == 'arm64' && matrix.pkgs == 'etcd' }}
        uses: actions/download-artifact@v5
        with:
          name: etcd-arm-source_tarball
          path: test/source_tarball/

      - name: Get source rpm from artifact
        if: ${{ contains(matrix.platform, 'linux') && matrix.arch == 'arm64' && matrix.pkgs == 'etcd' }}
        uses: actions/download-artifact@v5
        with:
          name: etcd-arm-srpm
          path: test/srpm/

      - name: Get source deb from artifact
        if: ${{ !contains(matrix.platform, 'linux') && matrix.arch == 'arm64' && matrix.pkgs == 'etcd' }}
        uses: actions/download-artifact@v5
        with:
          name: etcd-arm-source_deb
          path: test/source_deb/

      - name: Install dependencies
        run: |
          sudo bash ./pkg-builder.sh --builddir=$(pwd)/test --install_deps=1 --pg_major=${{ inputs.pg-major }}
        shell: bash

      - name: Build RPM/DEB
        continue-on-error: true
        run: |
          if [[ "${{ matrix.platform }}" == *"linux"* ]]; then
            sudo bash ./pkg-builder.sh --builddir=$(pwd)/test --build_rpm=1 --pg_major=${{ inputs.pg-major }}
          else
            sudo bash ./pkg-builder.sh --builddir=$(pwd)/test --build_deb=1 --pg_major=${{ inputs.pg-major }}
          fi
        shell: bash

      - name: Compute platform label
        run: |
          PLATFORM="${{ matrix.platform }}"
          if [[ "$PLATFORM" == *linux* ]]; then
            echo "PLATFORM_LABEL=ol${PLATFORM##*:}" >> "$GITHUB_ENV"
          else
            echo "PLATFORM_LABEL=${PLATFORM##*:}" >> "$GITHUB_ENV"
          fi
        shell: bash

      - name: Upload rpms as artifact
        if: ${{ contains(matrix.platform, 'linux') }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkgs }}-${{ env.PLATFORM_LABEL }}-${{ matrix.arch }}
          path: rpm

      - name: Upload debs as artifact
        if: ${{ !contains(matrix.platform, 'linux') }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkgs }}-${{ env.PLATFORM_LABEL }}-${{ matrix.arch }}
          path: deb

  upload-draft-release:
    runs-on: ubuntu-latest
    needs: [prepare-matrix, pull-build-files, build-source-tarball, build-srpm-sdeb, build-rpm-deb]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.PKG_MATRIX) }}

    steps:
     - name: Get build-files from artifact
       uses: actions/download-artifact@v5
       with:
        pattern: build-files-${{ matrix.pkgs }}
        path: ./

     - name: Get all the artifacts
       uses: actions/download-artifact@v5
       with:
        pattern: ${{ matrix.pkgs }}-*
        path: artifacts

     - name: Get package full name and upload path
       run: |
          PKG_UPPER=$(echo "${{ matrix.pkgs }}" | tr '[:lower:]-' '[:upper:]_')
          comp_version=$(grep "^${PKG_UPPER}_VERSION=" versions.sh | cut -d '=' -f2)
          pkg_name="${{ matrix.pkgs }}-$comp_version"
          echo "pkg_name=$pkg_name" >> "$GITHUB_ENV"
          echo "UPLOAD_PATH=common-pkg/${{ matrix.pkgs }}/$pkg_name/${{ needs.prepare-matrix.outputs.BUILD_ID }}" >> "$GITHUB_ENV"

     - name: Create final artifact structure
       run: |
        mkdir -p ${{ env.UPLOAD_PATH }}/source_tarball
        mkdir -p ${{ env.UPLOAD_PATH }}/srpm
        mkdir -p ${{ env.UPLOAD_PATH }}/source_deb
        mkdir -p ${{ env.UPLOAD_PATH }}/rpm
        mkdir -p ${{ env.UPLOAD_PATH }}/deb

     - name: Copy all the artifacts to required location
       run: |
          cp artifacts/${{ matrix.pkgs }}-source_tarball/* "${{ env.UPLOAD_PATH }}/source_tarball/"
          if [ "${{ inputs.distro }}" = "rpm" ] || [ "${{ inputs.distro }}" = "rpm-and-deb" ]; then
            cp -n artifacts/${{ matrix.pkgs }}-srpm/* "${{ env.UPLOAD_PATH }}/srpm/"
            cp -n artifacts/${{ matrix.pkgs }}-ol8-*/* "${{ env.UPLOAD_PATH }}/rpm/"
            cp -n artifacts/${{ matrix.pkgs }}-ol9-*/* "${{ env.UPLOAD_PATH }}/rpm/"
            cp -n artifacts/${{ matrix.pkgs }}-ol10-*/* "${{ env.UPLOAD_PATH }}/rpm/"
          fi
          if [ "${{ inputs.distro }}" = "deb" ] || [ "${{ inputs.distro }}" = "rpm-and-deb" ]; then
            cp -n artifacts/${{ matrix.pkgs }}-source_deb/* "${{ env.UPLOAD_PATH }}/source_deb/"
            cp -n artifacts/${{ matrix.pkgs }}-bookworm-*/* "${{ env.UPLOAD_PATH }}/deb/"
            cp -n artifacts/${{ matrix.pkgs }}-bullseye-*/* "${{ env.UPLOAD_PATH }}/deb/"
            cp -n artifacts/${{ matrix.pkgs }}-jammy-*/* "${{ env.UPLOAD_PATH }}/deb/"
            cp -n artifacts/${{ matrix.pkgs }}-noble-*/* "${{ env.UPLOAD_PATH }}/deb/"
            cp -n artifacts/${{ matrix.pkgs }}-trixie-*/* "${{ env.UPLOAD_PATH }}/deb/"
          fi

     - name: Archive final artifact
       run: tar -czf ${{ env.pkg_name }}.tar.gz common-pkg

     - name: Upload final artifact as release artifact
       uses: softprops/action-gh-release@v2
       with:
        draft: true
        tag_name: ${{ env.pkg_name }}-${{ inputs.distro }} build_id-${{ github.run_number }}
        name: ${{ env.pkg_name }}-${{ inputs.distro }} build_id-${{ github.run_number }}
        files: ${{ env.pkg_name }}.tar.gz

     - name: enable tmate debugging
       if: inputs.debugging && failure()
       uses: mxschmitt/action-tmate@v3
       timeout-minutes: 60