name: Build PPG Extras

on:
  workflow_dispatch:

jobs:
  dummy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print basic info
        run: |
          echo "Run this WF from respective <pg_version>-extras branch."
